#!/usr/bin/env bash
# Turns install-config.yaml into real ignition files, then uploads
# bootstrap.ign and master.ign to S3 for the bastion to pull down (see
# docs/architecture.md). worker.ign is generated by openshift-install
# regardless (compute.replicas=0 doesn't suppress it) but is never uploaded
# -- no worker nodes exist in this topology to fetch it.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
# shellcheck source=../lib/read-tfvars.sh
source "$repo_root/scripts/lib/read-tfvars.sh"

usage() {
  echo "usage: generate-ignition.sh -a <account-alias>"
  exit 1
}

account_alias=""
while [ $# -gt 0 ]; do
  case "$1" in
    -a)
      account_alias="$2"
      shift 2
      ;;
    *) usage ;;
  esac
done
[ -n "$account_alias" ] || usage

tfvars="$repo_root/accounts/${account_alias}.tfvars"
[ -f "$tfvars" ] || {
  echo "ERROR: $tfvars not found." >&2
  exit 1
}
region=$(read_tfvar aws_region "$tfvars")

dir="$repo_root/.ignition/${account_alias}"
[ -f "$dir/install-config.yaml" ] || {
  echo "ERROR: $dir/install-config.yaml not found -- run render-install-config.sh first." >&2
  exit 1
}

command -v openshift-install >/dev/null 2>&1 || {
  echo "ERROR: openshift-install not found on PATH." >&2
  exit 1
}

echo "Generating manifests..." >&2
openshift-install create manifests --dir "$dir"

# Masters resolve their real MachineConfig from https://api-int.<cluster
# domain>:22623 on first boot -- a name only the bastion's CoreDNS can
# answer. That fetch happens inside Ignition's own config.merge stage, which
# resolves before any Ignition-delivered file (e.g. a MachineConfig extra
# manifest) is ever written to disk -- confirmed for real: a MachineConfig-
# delivered DNS fix never arrived, stuck behind the exact fetch it was meant
# to unblock. The actual fix has to run before Ignition's network fetches
# start, so it's a kernel argument baked into the AMI (see
# scripts/ami-build/build-custom-ami.sh's --dns flag), not anything here.
echo "Generating ignition configs..." >&2
openshift-install create ignition-configs --dir "$dir"

bucket=$(cd "$repo_root/terraform" && terraform output -raw ignition_bucket_name)

echo "Uploading bootstrap.ign and master.ign to s3://${bucket}/ignition/ ..." >&2
aws s3 cp "$dir/bootstrap.ign" "s3://${bucket}/ignition/bootstrap.ign" --region "$region"
aws s3 cp "$dir/master.ign" "s3://${bucket}/ignition/master.ign" --region "$region"

echo "Done." >&2
echo "kubeconfig:          $dir/auth/kubeconfig" >&2
echo "kubeadmin password:  $dir/auth/kubeadmin-password" >&2
